version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - ai-ml
      - blockchain

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: fakedegrees
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  ai-ml:
    build: ./backend/ai_ml_service   # if you have AI folder
    ports:
      - "8000:8000"

  blockchain:
    build: ./backend/blockchain_service/certificate_verification_system
    ports:
      - "9000:9000"

volumes:
  dbdata:
