version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WEB3_PROVIDER=http://ganache:8545
      - CONTRACT_ADDRESS=__REPLACE__
    depends_on:
      - ganache
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ["--deterministic", "-p", "8545"]
    ports:
      - "8545:8545"
